name = "habit-pilot"
main = ".open-next/worker.js"
compatibility_date = "2026-02-17"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "habit-pilot"
database_id = "866e1cec-0ea5-4c30-b586-02e296c7ba92"
migrations_dir = "drizzle"
remote = true
