name = "habit-pilot"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "habit-pilot"
database_id = "habit-pilot"
migrations_dir = "drizzle"
